# Generated by Django 4.0.4 on 2022-05-29 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20)),
                ('userID', models.CharField(default='', max_length=20)),
                ('datetime', models.IntegerField(default=11)),
                ('sTable', models.IntegerField(default=0)),
                ('isSReg', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialcode', models.CharField(max_length=20)),
                ('genTime', models.IntegerField(default=202205291216)),
            ],
        ),
        migrations.CreateModel(
            name='Serialtable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentSerial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.serial')),
            ],
        ),
    ]
