# Generated by Django 4.0.4 on 2022-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_serial_gentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='genTime',
            field=models.CharField(default='202205291219', max_length=20),
        ),
    ]
