# Generated by Django 4.0.4 on 2022-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_serial_gentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='genTime',
            field=models.CharField(default='2205291219', max_length=20),
        ),
        migrations.AlterField(
            model_name='serial',
            name='serialcode',
            field=models.CharField(max_length=16),
        ),
    ]
