# Generated by Django 3.1.3 on 2022-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_serial_gentime_alter_serial_serialcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='serialcode',
            field=models.CharField(max_length=20),
        ),
    ]
